# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: triton-model-pv
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: "az-a"
#   hostPath:
#     path: "/mnt/disks/triton-models"

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: triton-model-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: az-a
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 19Gi
      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-model-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-external-storagecluster-cephfs  # e.g., ocs-storagecluster-cephfs, azurefile-csi, nfs
  resources:
    requests:
      storage: 20Gi